const totalItemInDb = [
  { id: 1, name: 'Apple', category: 'Fruit', available: true },
  { id: 2, name: 'Banana', category: 'Fruit', available: true },
  { id: 3, name: 'Carrot', category: 'Vegetable', available: true },
  { id: 4, name: 'Broccoli', category: 'Vegetable', available: false },
  { id: 5, name: 'Orange', category: 'Fruit', available: false },
  { id: 6, name: 'Grapes', category: 'Fruit', available: true },
  { id: 7, name: 'Cabbage', category: 'Vegetable', available: true },
  { id: 8, name: 'Strawberry', category: 'Fruit', available: true },
  { id: 9, name: 'Spinach', category: 'Vegetable', available: false },
  { id: 10, name: 'Pear', category: 'Fruit', available: true },
  { id: 11, name: 'Tomato', category: 'Vegetable', available: true },
  { id: 12, name: 'Watermelon', category: 'Fruit', available: true },
  { id: 13, name: 'Potato', category: 'Vegetable', available: false },
  { id: 14, name: 'Pineapple', category: 'Fruit', available: true },
  { id: 15, name: 'Cauliflower', category: 'Vegetable', available: true },
  { id: 16, name: 'Mango', category: 'Fruit', available: false },
  { id: 17, name: 'Lettuce', category: 'Vegetable', available: true },
  { id: 18, name: 'Kiwi', category: 'Fruit', available: true },
  { id: 19, name: 'Cucumber', category: 'Vegetable', available: false },
  { id: 20, name: 'Cherry', category: 'Fruit', available: true },
];


export default totalItemInDb;

export const apiLocalPath='https://4380-183-83-219-106.ngrok-free.app';
export const objectDetectionProbability = {
  objectName: [
    "Apple",
    "Banana",
    "Orange",
    "Grapes",
    "Strawberry",
    "Mango",
    "Watermelon",
    "Pineapple",
    "Cherry",
    "Peach",
    "Pear",
    "Kiwi",
    "Blueberry",
    "Raspberry",
    "Blackberry",
    "Plum",
    "Lemon",
    "Lime",
    "Coconut",
    "Pomegranate",
    "Cantaloupe",
    "Honeydew",
    "Fig",
    "Avocado",
    "Papaya",
    "Guava",
    "Passion Fruit",
    "Dragon Fruit",
    "Lychee",
    "Apricot",
    "Nectarine",
    "Cranberry",
    "Raspberry",
    "Gooseberry",
    "Pineapple",
    "Mandarin",
    "Clementine",
    "Tangerine",
    "Mulberry",
    "Star Fruit"
  ],
  objectProbability: [
    0.67,
    0.75,
    0.89,
    0.58,
    0.92,
    0.61,
    0.84,
    0.78,
    0.73,
    0.56,
    0.8,
    0.51,
    0.91,
    0.86,
    0.7,
    0.62,
    0.94,
    0.76,
    0.53,
    0.83,
    0.68,
    0.88,
    0.59,
    0.72,
    0.96,
    0.87,
    0.66,
    0.55,
    0.81,
    0.97,
    0.71,
    0.54,
    0.95,
    0.79,
    0.69,
    0.74,
    0.63,
    0.85,
    0.52,
    0.9,
    0.65,
  ]
}